name: business_card
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ava.png
  fonts: 
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Light.ttf
    - family: CVIcons
      fonts: 
        - asset: icons/CVIcons.ttf